import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import '../../domain/entities/booking_entity.dart';
import '../bloc/booking_bloc.dart';
import '../bloc/booking_event.dart';
import '../bloc/booking_state.dart';

class BookingPage extends StatefulWidget {
  final String hotelId;
  final String roomId;
  final double pricePerNight;

  const BookingPage({
    super.key,
    required this.hotelId,
    required this.roomId,
    required this.pricePerNight,
  });

  @override
  State<BookingPage> createState() => _BookingPageState();
}

class _BookingPageState extends State<BookingPage> {
  DateTimeRange? _selectedDateRange;
  int _guestCount = 1;

  void _selectDates() async {
    final picked = await showDateRangePicker(
      context: context,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );

    if (picked != null) {
      setState(() {
        _selectedDateRange = picked;
      });
      context.read<BookingBloc>().add(CheckAvailability(
            roomId: widget.roomId,
            checkIn: picked.start,
            checkOut: picked.end,
          ));
    }
  }

  void _createBooking() {
    if (_selectedDateRange == null) return;

    final nights = _selectedDateRange!.duration.inDays;
    final totalPrice = nights * widget.pricePerNight;

    final booking = BookingEntity(
      id: '', // Generated by backend
      userId: '', // Set by backend/repository
      hotelId: widget.hotelId,
      roomId: widget.roomId,
      checkIn: _selectedDateRange!.start,
      checkOut: _selectedDateRange!.end,
      guestCount: _guestCount,
      totalPrice: totalPrice,
      status: 'pending',
      createdAt: DateTime.now(),
    );

    context.read<BookingBloc>().add(CreateBooking(booking));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Book Room')),
      body: BlocConsumer<BookingBloc, BookingState>(
        listener: (context, state) {
          if (state is BookingSuccess) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Booking Confirmed!')),
            );
            context.go('/bookings');
          } else if (state is BookingFailure) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text(state.message)),
            );
          }
        },
        builder: (context, state) {
          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Date Selection
                ListTile(
                  title: Text(_selectedDateRange == null
                      ? 'Select Dates'
                      : '${_selectedDateRange!.start.toString().split(' ')[0]} - ${_selectedDateRange!.end.toString().split(' ')[0]}'),
                  trailing: const Icon(Icons.calendar_today),
                  onTap: _selectDates,
                ),
                const Divider(),
                // Guest Count
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text('Guests'),
                    Row(
                      children: [
                        IconButton(
                          icon: const Icon(Icons.remove),
                          onPressed: _guestCount > 1
                              ? () => setState(() => _guestCount--)
                              : null,
                        ),
                        Text('$_guestCount'),
                        IconButton(
                          icon: const Icon(Icons.add),
                          onPressed: () => setState(() => _guestCount++),
                        ),
                      ],
                    ),
                  ],
                ),
                const Divider(),
                // Availability Status
                if (state is BookingLoading)
                  const Center(child: CircularProgressIndicator())
                else if (state is AvailabilityChecked)
                  Text(
                    state.isAvailable ? 'Available' : 'Not Available',
                    style: TextStyle(
                      color: state.isAvailable ? Colors.green : Colors.red,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                const Spacer(),
                // Price Summary
                if (_selectedDateRange != null) ...[
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text('Total Price'),
                      Text(
                        '\$${(_selectedDateRange!.duration.inDays * widget.pricePerNight).toStringAsFixed(2)}',
                        style: const TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: (state is AvailabilityChecked &&
                              state.isAvailable)
                          ? _createBooking
                          : null,
                      child: const Text('Confirm Booking'),
                    ),
                  ),
                ],
              ],
            ),
          );
        },
      ),
    );
  }
}
