// Mocks generated by Mockito 5.4.6 from annotations
// in hotel_booking/test/features/payments/data/repositories/payment_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hotel_booking/features/payments/data/datasources/payment_remote_data_source.dart'
    as _i3;
import 'package:hotel_booking/features/payments/data/models/payment_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaymentModel_0 extends _i1.SmartFake implements _i2.PaymentModel {
  _FakePaymentModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRemoteDataSource extends _i1.Mock
    implements _i3.PaymentRemoteDataSource {
  MockPaymentRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaymentModel> initiatePayment(_i2.PaymentModel? payment) =>
      (super.noSuchMethod(
            Invocation.method(#initiatePayment, [payment]),
            returnValue: _i4.Future<_i2.PaymentModel>.value(
              _FakePaymentModel_0(
                this,
                Invocation.method(#initiatePayment, [payment]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentModel>);

  @override
  _i4.Future<_i2.PaymentModel> verifyPayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPayment, [paymentId]),
            returnValue: _i4.Future<_i2.PaymentModel>.value(
              _FakePaymentModel_0(
                this,
                Invocation.method(#verifyPayment, [paymentId]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentModel>);

  @override
  _i4.Future<_i2.PaymentModel> getPaymentStatus(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatus, [paymentId]),
            returnValue: _i4.Future<_i2.PaymentModel>.value(
              _FakePaymentModel_0(
                this,
                Invocation.method(#getPaymentStatus, [paymentId]),
              ),
            ),
          )
          as _i4.Future<_i2.PaymentModel>);
}
