// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6LDaXwnptgR4YUOqxfCwaDVWycpH0Pc',
    appId: '1:484058026308:web:23f69ed377bf736af84711',
    messagingSenderId: '484058026308',
    projectId: 'chat-app-f759e',
    authDomain: 'chat-app-f759e.firebaseapp.com',
    storageBucket: 'chat-app-f759e.firebasestorage.app',
    measurementId: 'G-WE46VBP4MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXpJsEU27_ZNdhlWF3MgDYZI1hg8BZQ0',
    appId: '1:484058026308:android:1c6ee63bdc44ca05f84711',
    messagingSenderId: '484058026308',
    projectId: 'chat-app-f759e',
    storageBucket: 'chat-app-f759e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8_n46zm0wL1UUYaxOVjGD2mZ7zN1TLQ',
    appId: '1:484058026308:ios:f911891ac27be2dcf84711',
    messagingSenderId: '484058026308',
    projectId: 'chat-app-f759e',
    storageBucket: 'chat-app-f759e.firebasestorage.app',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8_n46zm0wL1UUYaxOVjGD2mZ7zN1TLQ',
    appId: '1:484058026308:ios:f911891ac27be2dcf84711',
    messagingSenderId: '484058026308',
    projectId: 'chat-app-f759e',
    storageBucket: 'chat-app-f759e.firebasestorage.app',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw6LDaXwnptgR4YUOqxfCwaDVWycpH0Pc',
    appId: '1:484058026308:web:ed25a82faaff11e2f84711',
    messagingSenderId: '484058026308',
    projectId: 'chat-app-f759e',
    authDomain: 'chat-app-f759e.firebaseapp.com',
    storageBucket: 'chat-app-f759e.firebasestorage.app',
    measurementId: 'G-BF1EQDVWPZ',
  );
}
