// Mocks generated by Mockito 5.4.6 from annotations
// in hotel_booking/test/features/owner/domain/usecases/get_owner_hotels_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:hotel_booking/core/error/failures.dart' as _i5;
import 'package:hotel_booking/features/owner/domain/entities/owner_hotel.dart'
    as _i6;
import 'package:hotel_booking/features/owner/domain/entities/room.dart' as _i8;
import 'package:hotel_booking/features/owner/domain/repositories/owner_hotel_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OwnerHotelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerHotelRepository extends _i1.Mock
    implements _i2.OwnerHotelRepository {
  MockOwnerHotelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.OwnerHotel>>> getOwnerHotels(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnerHotels, [ownerId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.OwnerHotel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.OwnerHotel>>>(
                    this,
                    Invocation.method(#getOwnerHotels, [ownerId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.OwnerHotel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.OwnerHotel>> createHotel(
    _i6.OwnerHotel? hotel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createHotel, [hotel]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.OwnerHotel>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.OwnerHotel>>(
                    this,
                    Invocation.method(#createHotel, [hotel]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.OwnerHotel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.OwnerHotel>> updateHotel(
    _i6.OwnerHotel? hotel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateHotel, [hotel]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.OwnerHotel>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.OwnerHotel>>(
                    this,
                    Invocation.method(#updateHotel, [hotel]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.OwnerHotel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.Room>>> getRooms(
    String? hotelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRooms, [hotelId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.Room>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.Room>>>(
                    this,
                    Invocation.method(#getRooms, [hotelId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.Room>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.Room>> addRoom(_i8.Room? room) =>
      (super.noSuchMethod(
            Invocation.method(#addRoom, [room]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i8.Room>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i8.Room>>(
                this,
                Invocation.method(#addRoom, [room]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.Room>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.Room>> updateRoom(_i8.Room? room) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoom, [room]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i8.Room>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i8.Room>>(
                this,
                Invocation.method(#updateRoom, [room]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.Room>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.Room>> toggleRoomAvailability(
    String? roomId,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRoomAvailability, [roomId, isAvailable]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i8.Room>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i8.Room>>(
                this,
                Invocation.method(#toggleRoomAvailability, [
                  roomId,
                  isAvailable,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.Room>>);
}
