// Mocks generated by Mockito 5.4.6 from annotations
// in hotel_booking/test/features/wallet/data/repositories/wallet_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hotel_booking/features/wallet/data/datasources/wallet_remote_data_source.dart'
    as _i3;
import 'package:hotel_booking/features/wallet/data/models/transaction_model.dart'
    as _i5;
import 'package:hotel_booking/features/wallet/data/models/wallet_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWalletModel_0 extends _i1.SmartFake implements _i2.WalletModel {
  _FakeWalletModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRemoteDataSource extends _i1.Mock
    implements _i3.WalletRemoteDataSource {
  MockWalletRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WalletModel> getWallet(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, [userId]),
            returnValue: _i4.Future<_i2.WalletModel>.value(
              _FakeWalletModel_0(this, Invocation.method(#getWallet, [userId])),
            ),
          )
          as _i4.Future<_i2.WalletModel>);

  @override
  _i4.Future<_i2.WalletModel> addFunds(
    String? userId,
    double? amount,
    String? currency,
    String? paymentMethodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addFunds, [
              userId,
              amount,
              currency,
              paymentMethodId,
            ]),
            returnValue: _i4.Future<_i2.WalletModel>.value(
              _FakeWalletModel_0(
                this,
                Invocation.method(#addFunds, [
                  userId,
                  amount,
                  currency,
                  paymentMethodId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.WalletModel>);

  @override
  _i4.Future<List<_i5.TransactionModel>> getTransactionHistory(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionHistory, [userId]),
            returnValue: _i4.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i5.TransactionModel>>);
}
