// Mocks generated by Mockito 5.4.6 from annotations
// in hotel_booking/test/features/owner/data/repositories/owner_hotel_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hotel_booking/features/owner/data/datasources/owner_remote_data_source.dart'
    as _i5;
import 'package:hotel_booking/features/owner/data/models/owner_booking_model.dart'
    as _i7;
import 'package:hotel_booking/features/owner/data/models/owner_hotel_model.dart'
    as _i2;
import 'package:hotel_booking/features/owner/data/models/revenue_summary_model.dart'
    as _i4;
import 'package:hotel_booking/features/owner/data/models/room_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOwnerHotelModel_0 extends _i1.SmartFake
    implements _i2.OwnerHotelModel {
  _FakeOwnerHotelModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoomModel_1 extends _i1.SmartFake implements _i3.RoomModel {
  _FakeRoomModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRevenueSummaryModel_2 extends _i1.SmartFake
    implements _i4.RevenueSummaryModel {
  _FakeRevenueSummaryModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OwnerRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerRemoteDataSource extends _i1.Mock
    implements _i5.OwnerRemoteDataSource {
  MockOwnerRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.OwnerHotelModel>> getOwnerHotels(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnerHotels, [ownerId]),
            returnValue: _i6.Future<List<_i2.OwnerHotelModel>>.value(
              <_i2.OwnerHotelModel>[],
            ),
          )
          as _i6.Future<List<_i2.OwnerHotelModel>>);

  @override
  _i6.Future<_i2.OwnerHotelModel> createHotel(_i2.OwnerHotelModel? hotel) =>
      (super.noSuchMethod(
            Invocation.method(#createHotel, [hotel]),
            returnValue: _i6.Future<_i2.OwnerHotelModel>.value(
              _FakeOwnerHotelModel_0(
                this,
                Invocation.method(#createHotel, [hotel]),
              ),
            ),
          )
          as _i6.Future<_i2.OwnerHotelModel>);

  @override
  _i6.Future<_i2.OwnerHotelModel> updateHotel(_i2.OwnerHotelModel? hotel) =>
      (super.noSuchMethod(
            Invocation.method(#updateHotel, [hotel]),
            returnValue: _i6.Future<_i2.OwnerHotelModel>.value(
              _FakeOwnerHotelModel_0(
                this,
                Invocation.method(#updateHotel, [hotel]),
              ),
            ),
          )
          as _i6.Future<_i2.OwnerHotelModel>);

  @override
  _i6.Future<List<_i3.RoomModel>> getRooms(String? hotelId) =>
      (super.noSuchMethod(
            Invocation.method(#getRooms, [hotelId]),
            returnValue: _i6.Future<List<_i3.RoomModel>>.value(
              <_i3.RoomModel>[],
            ),
          )
          as _i6.Future<List<_i3.RoomModel>>);

  @override
  _i6.Future<_i3.RoomModel> addRoom(_i3.RoomModel? room) =>
      (super.noSuchMethod(
            Invocation.method(#addRoom, [room]),
            returnValue: _i6.Future<_i3.RoomModel>.value(
              _FakeRoomModel_1(this, Invocation.method(#addRoom, [room])),
            ),
          )
          as _i6.Future<_i3.RoomModel>);

  @override
  _i6.Future<_i3.RoomModel> updateRoom(_i3.RoomModel? room) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoom, [room]),
            returnValue: _i6.Future<_i3.RoomModel>.value(
              _FakeRoomModel_1(this, Invocation.method(#updateRoom, [room])),
            ),
          )
          as _i6.Future<_i3.RoomModel>);

  @override
  _i6.Future<_i3.RoomModel> toggleRoomAvailability(
    String? roomId,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRoomAvailability, [roomId, isAvailable]),
            returnValue: _i6.Future<_i3.RoomModel>.value(
              _FakeRoomModel_1(
                this,
                Invocation.method(#toggleRoomAvailability, [
                  roomId,
                  isAvailable,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.RoomModel>);

  @override
  _i6.Future<List<_i7.OwnerBookingModel>> getOwnerBookings(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnerBookings, [ownerId]),
            returnValue: _i6.Future<List<_i7.OwnerBookingModel>>.value(
              <_i7.OwnerBookingModel>[],
            ),
          )
          as _i6.Future<List<_i7.OwnerBookingModel>>);

  @override
  _i6.Future<_i4.RevenueSummaryModel> getRevenueSummary(
    String? ownerId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRevenueSummary, [ownerId, start, end]),
            returnValue: _i6.Future<_i4.RevenueSummaryModel>.value(
              _FakeRevenueSummaryModel_2(
                this,
                Invocation.method(#getRevenueSummary, [ownerId, start, end]),
              ),
            ),
          )
          as _i6.Future<_i4.RevenueSummaryModel>);
}
