// Mocks generated by Mockito 5.4.6 from annotations
// in hotel_booking/test/features/payments/domain/usecases/verify_payment_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:hotel_booking/core/error/failures.dart' as _i5;
import 'package:hotel_booking/features/payments/domain/entities/payment_entity.dart'
    as _i6;
import 'package:hotel_booking/features/payments/domain/repositories/payment_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i2.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>> initiatePayment({
    required String? bookingId,
    required double? amount,
    required String? currency,
    required String? method,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiatePayment, [], {
              #bookingId: bookingId,
              #amount: amount,
              #currency: currency,
              #method: method,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.PaymentEntity>>(
                    this,
                    Invocation.method(#initiatePayment, [], {
                      #bookingId: bookingId,
                      #amount: amount,
                      #currency: currency,
                      #method: method,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>> verifyPayment(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPayment, [paymentId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.PaymentEntity>>(
                    this,
                    Invocation.method(#verifyPayment, [paymentId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>> getPaymentStatus(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatus, [paymentId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.PaymentEntity>>(
                    this,
                    Invocation.method(#getPaymentStatus, [paymentId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.PaymentEntity>>);
}
